baseURL = "https://shingo-omata.github.io/hugo-test/"
languageCode = "ja-jp"
title = "omathin hugo-test"
author = "omathin"
canonifyurls = true
paginate = 3
theme = "syna"
publishDir = "docs"
hasCJKLanguage = true

